// Code generated by "stringer -type BinaryOperator -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinAdd-1]
	_ = x[BinSub-2]
	_ = x[BinMul-3]
	_ = x[BinDiv-4]
	_ = x[BinMod-5]
	_ = x[BinOr-6]
	_ = x[BinXor-7]
	_ = x[BinAnd-8]
	_ = x[BinShl-9]
	_ = x[BinShr-10]
	_ = x[BinCeq-11]
	_ = x[BinCne-12]
	_ = x[BinClt-13]
	_ = x[BinCgt-14]
	_ = x[BinCle-15]
	_ = x[BinCge-16]
	_ = x[BinaryOperatorMax-17]
}

const _BinaryOperator_name = "+-*/%|^&<<>>==!=<><=>=BinaryOperatorMax"

var _BinaryOperator_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 17, 18, 20, 22, 39}

func (i BinaryOperator) String() string {
	i -= 1
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
