// Code generated by "stringer -type BooleanOperator -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BoolAnd-1]
	_ = x[BoolOr-2]
	_ = x[BooleanOperatorMax-3]
}

const _BooleanOperator_name = "&&||BooleanOperatorMax"

var _BooleanOperator_index = [...]uint8{0, 2, 4, 22}

func (i BooleanOperator) String() string {
	i -= 1
	if i < 0 || i >= BooleanOperator(len(_BooleanOperator_index)-1) {
		return "BooleanOperator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BooleanOperator_name[_BooleanOperator_index[i]:_BooleanOperator_index[i+1]]
}
