// Code generated by "stringer -type PrefixOperator -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrefNot-1]
	_ = x[PrefInv-2]
	_ = x[PrefNeg-3]
	_ = x[PrefPos-4]
	_ = x[PrefixOperatorMax-5]
}

const _PrefixOperator_name = "!^-+PrefixOperatorMax"

var _PrefixOperator_index = [...]uint8{0, 1, 2, 3, 4, 21}

func (i PrefixOperator) String() string {
	i -= 1
	if i < 0 || i >= PrefixOperator(len(_PrefixOperator_index)-1) {
		return "PrefixOperator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PrefixOperator_name[_PrefixOperator_index[i]:_PrefixOperator_index[i+1]]
}
