// Code generated by "stringer -type TokenType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TEOF-0]
	_ = x[TComment-1]
	_ = x[TSpace-2]
	_ = x[TNewline-3]
	_ = x[TBackslash-4]
	_ = x[TSemi-5]
	_ = x[TComma-6]
	_ = x[TLParen-7]
	_ = x[TRParen-8]
	_ = x[TLSquare-9]
	_ = x[TRSquare-10]
	_ = x[TLBrace-11]
	_ = x[TRBrace-12]
	_ = x[TIdent-13]
	_ = x[TType-14]
	_ = x[TString-15]
	_ = x[TRune-16]
	_ = x[TFloat-17]
	_ = x[TInteger-18]
	_ = x[TMadd-19]
	_ = x[TMsub-20]
	_ = x[TMmul-21]
	_ = x[TMdiv-22]
	_ = x[TMmod-23]
	_ = x[TMor-24]
	_ = x[TMxor-25]
	_ = x[TMand-26]
	_ = x[TMshl-27]
	_ = x[TMshr-28]
	_ = x[TMland-29]
	_ = x[TMlor-30]
	_ = x[TShl-31]
	_ = x[TShr-32]
	_ = x[TLand-33]
	_ = x[TLor-34]
	_ = x[TCeq-35]
	_ = x[TCne-36]
	_ = x[TCle-37]
	_ = x[TCge-38]
	_ = x[TEquals-39]
	_ = x[TPlus-40]
	_ = x[TMinus-41]
	_ = x[TAster-42]
	_ = x[TSlash-43]
	_ = x[TPerc-44]
	_ = x[TExcl-45]
	_ = x[TPipe-46]
	_ = x[TCaret-47]
	_ = x[TAmp-48]
	_ = x[TLess-49]
	_ = x[TGreater-50]
	_ = x[TDot-51]
	_ = x[TInvalid-52]
	_ = x[LexTokenMax-53]
	_ = x[TKeywordStart-54]
	_ = x[TKelse-55]
	_ = x[TKextern-56]
	_ = x[TKfn-57]
	_ = x[TKfor-58]
	_ = x[TKif-59]
	_ = x[TKns-60]
	_ = x[TKpub-61]
	_ = x[TKreturn-62]
	_ = x[TKstruct-63]
	_ = x[TKtype-64]
	_ = x[TKunion-65]
	_ = x[TKvar-66]
	_ = x[TKvariadic-67]
	_ = x[TKeywordEnd-68]
}

const _TokenType_name = "end of filecommentwhitespacenewline'\\'';'',''('')''['']''{''}'identifiertype namestring literalcharacter literalfloat literalinteger literal'+=''-=''*=''/=''%=''|=''^=''&=''<<=''>>=''&&=''||=''<<''>>''&&''||''==''!=''<=''>=''=''+''-''*''/''%''!''|''^''&''<''>''.'invalid tokenLexTokenMaxTKeywordStart'else''extern''fn''for''if''ns''pub''return''struct''type''union''var''variadic'TKeywordEnd"

var _TokenType_index = [...]uint16{0, 11, 18, 28, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 72, 81, 95, 112, 125, 140, 144, 148, 152, 156, 160, 164, 168, 172, 177, 182, 187, 192, 196, 200, 204, 208, 212, 216, 220, 224, 227, 230, 233, 236, 239, 242, 245, 248, 251, 254, 257, 260, 263, 276, 287, 300, 306, 314, 318, 323, 327, 331, 336, 344, 352, 358, 365, 370, 380, 391}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
